extends Node

#==== Card Prefabs ====#
const _active_card = preload("res://GameObjects/Card/ActiveCard/ActiveCard.tscn")
const _growth_card = preload("res://GameObjects/Card/GrowthCard/GrowthCard.tscn")
const _fungi_card = preload("res://GameObjects/Card/FungiCard/FungiCard.tscn")
const _weather_card = preload("res://GameObjects/Card/WeatherCard/WeatherCard.tscn")

#==== Sorted Lists ====#
var _cards_by_value = []

#==== Active Data ====#
var _active_type_ids = [
	"Common", 
	"Uncommon", 
	"Rare",
	"Epic",
	"Legendary"
]

#==== Default Cards ====#
var _def_active_cards = {}
var _def_growth_cards = {}
var _def_fungi_cards = {}
var _def_weather_cards = {}
var _total_cards = 0



#==== Bootstrap ====#

func _ready():
	load_default_cards()
	_cards_by_value = sort_cards_by_value()


func load_default_cards():
	load_default_active_cards()
	load_default_growth_cards()
	load_default_fungi_cards()
	load_default_weather_cards()


func load_default_active_cards():
	var active_dict = [
		{
		"id": 0,
		"card_name": "Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 1,
		"value": 1,
		"effect": 1,
		"effect_description": "",
		"image_id": 0
		},
		{
		"id": 1,
		"card_name": "Army Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 3,
		"value": 1,
		"effect": 2,
		"effect_description": "Trample (If this card defeats an opponent's active card, it deals the leftover robustness to the Growth card behind it)",
		"image_id": 0
		},		{
		"id": 2,
		"card_name": "Queen Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 5,
		"value": 2,
		"effect": 2,
		"effect_description": "Trample (If this card defeats an opponent's active card, it deals the leftover robustness to the Growth card behind it)",
		"image_id": 0
		},
		{
		"id": 3,
		"card_name": "Cricket",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 2,
		"value": 1,
		"effect": 3,
		"effect_description": "No Latency (This card can activate or attack on the turn it is summoned)",
		"image_id": 0
		},
		{
		"id": 4,
		"card_name": "Newton",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 2,
		"value": 1,
		"effect": 4,
		"effect_description": "Shield (the first time this active card takes damage, the damage is reduced to 0, it then looses this ability)",
		"image_id": 0
		},
		{
		"id": 5,
		"card_name": "Owl",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 3,
		"value": 1,
		"effect": 5,
		"effect_description": "Direct attack (this active card can attack an oponent's growth card directly)",
		"image_id": 0
		},
		{
		"id": 6,
		"card_name" : "",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 2,
		"value": 1,
		"effect": 6,
		"effect_description": "When summoned, this card increases its robustness by 3 until the start of its next turn",
		"image_id": 0
		},
		{
		"id": 7,
		"card_name": "Bees",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 4,
		"value": 1,
		"effect": 7,
		"effect_description": "Target active Card gains gains No Latency",
		"image_id": 0
		},
		{
		"id": 8,
		"card_name": "Rabbit Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 3,
		"value": 1,
		"effect": 8,
		"effect_description": "Remove 1 Latency to each growth on your side of the field",
		"image_id": 0
		},
		{
		"id": 9,
		"card_name": "Beaver",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 5,
		"value": 1,
		"effect": 9,
		"effect_description": "Choose one tapped Growth Card and untap it",
		"image_id": 0
		},
		{
		"id": 10,
		"card_name": "Wasp",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 4,
		"value": 1,
		"effect": 10,
		"effect_description": "Choose an active card and poison it (it is destroyed in 2 turns)",
		"image_id": 0
		},
		{
		"id": 11,
		"card_name": "Badger",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 4,
		"value": 1,
		"effect": 11,
		"effect_description": "Restores 1 card from Extinction Deck",
		"image_id": 0
		},
		{
		"id": 12,
		"card_name": "Squirrel",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 2,
		"value": 1,
		"effect": 12,
		"effect_description": "Target Growth card doubles its energy during turn",
		"image_id": 0
		},
		{
		"id": 13,
		"card_name": "Poisonous Dart Frog",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 5,
		"value": 1,
		"effect": 13,
		"effect_description": "Remove target Active card from play",
		"image_id": 0
		},
		{
		"id": 14,
		"card_name": "Sheep",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 5,
		"value": 1,
		"effect": 14,
		"effect_description": "Deal 1 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 15,
		"card_name": "Cricket Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 6,
		"value": 1,
		"effect": 15,
		"effect_description": "Deal 2 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 16,
		"card_name": "Cricket Plague",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 7,
		"value": 1,
		"effect": 16,
		"effect_description": "Deal 1 damage to all Growth Cards",
		"image_id": 0
		},
		{
		"id": 17,
		"card_name": "Cat",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 3,
		"value": 1,
		"effect": 17,
		"effect_description": "Deal 2 damage to Active card",
		"image_id": 0
		},
		{
		"id": 18,
		"card_name": "Jackal",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 4,
		"value": 1,
		"effect": 18,
		"effect_description": "Deal 3 damage to Active card",
		"image_id": 0
		},
		{
		"id": 19,
		"card_name": "Pig",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 3,
		"value": 1,
		"effect": 19,
		"effect_description": "Destroy target Fauna and Fungi card in an active field",
		"image_id": 0
		},
		{
		"id": 20,
		"card_name": "Scorpion",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 5,
		"value": 1,
		"effect": 20,
		"effect_description": "Poison touch (an active or growth card that takes damage from this card is destroyed in two turns)",
		"image_id": 0
		},
		{
		"id": 21,
		"card_name": "Spider Monkey",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 5,
		"value": 1,
		"effect": 21,
		"effect_description": "Target Growth card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 22,
		"card_name": "Goose",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 4,
		"value": 1,
		"effect": 22,
		"effect_description": "Target Active card must be payed or be turned if its energy cost isnt payed.",
		"image_id": 0
		},
		{
		"id": 23,
		"card_name": "Mosquito Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 1,
		"value": 1,
		"effect": 23,
		"effect_description": "No Latency, this cards is destyed at the end of the turn.",
		"image_id": 0
		},
		{
		"id": 24,
		"card_name": "Migrating Flock",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 4,
		"value": 1,
		"effect": 24,
		"effect_description": "Each player draws 3 growth Cards and replaces all three active growth cards",
		"image_id": 0
		},
		{
		"id": 25,
		"card_name": "Cocoon",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 3,
		"value": 1,
		"effect": 25,
		"effect_description": "Each player draws 1 card from Active deck",
		"image_id": 0
		},
		{
		"id": 26,
		"card_name": "Metamorphosis",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 3,
		"value": 1,
		"effect": 26,
		"effect_description": "Target player draws 2 cards from Active deck",
		"image_id": 0
		},
		{
		"id": 27,
		"card_name": "Woodpecker",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 3,
		"value": 1,
		"effect": 27,
		"effect_description": "Target player draws 1 growth card",
		"image_id": 0
		},
		{
		"id": 28,
		"card_name": "Swallow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 4,
		"value": 1,
		"effect": 28,
		"effect_description": "Target player draws 2 growth cards",
		"image_id": 0
		},
		{
		"id": 29,
		"card_name": "Dung Beetle",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 4,
		"value": 1,
		"effect": 29,
		"effect_description": "Target Growth card gains Shield.",
		"image_id": 0
		},
		{
		"id": 30,
		"card_name": "Mole",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 3,
		"value": 1,
		"effect": 30,
		"effect_description": "Target Growth Card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 31,
		"card_name": "Snake Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 5,
		"value": 1,
		"effect": 31,
		"effect_description": "Target Growth card gains Shield",
		"image_id": 0
		},
		{
		"id": 32,
		"card_name": "Leaf Bug",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 5,
		"value": 1,
		"effect": 32,
		"effect_description": "When this card is destroyed it becomes a Fauna and Fungos card with the effect, you can tap this card to add 2 energy to one summoning.",
		"image_id": 0
		},
		{
		"id": 33,
		"card_name": "Termite",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 1,
		"type_name": "Active",
		"cost": 2,
		"value": 1,
		"effect": 33,
		"effect_description": "Deals double damage to Growth",
		"image_id": 0
		},
		{
		"id": 34,
		"card_name": "Giant Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 2,
		"value": 2,
		"effect": 1,
		"effect_description": "",
		"image_id": 0
		},
		{
		"id": 35,
		"card_name": "Giant Army Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 4,
		"value": 2,
		"effect": 2,
		"effect_description": "Trample (If this card defeats an opponent's active card, it deals the leftover robustness to the Growth card behind it)",
		"image_id": 0
		},
		{
		"id": 36,
		"card_name": "Giant Cricket",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 3,
		"value": 2,
		"effect": 3,
		"effect_description": "No Latency (This card can activate or attack on the turn it is summoned)",
		"image_id": 0
		},
		{
		"id": 37,
		"card_name": "Giant Newton",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 3,
		"value": 2,
		"effect": 4,
		"effect_description": "Shield (the first time this active card takes damage, the damage is reduced to 0, it then looses this ability)",
		"image_id": 0
		},
		{
		"id": 38,
		"card_name": "Giant Owl",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 4,
		"value": 2,
		"effect": 5,
		"effect_description": "Direct attack (this active card can attack an oponent's growth card directly)",
		"image_id": 0
		},
		{
		"id": 39,
		"card_name" : "",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 3,
		"value": 2,
		"effect": 6,
		"effect_description": "When summoned, this card increases its robustness by 3 until the start of its next turn",
		"image_id": 0
		},
		{
		"id": 40,
		"card_name": "Giant Bees",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 5,
		"value": 2,
		"effect": 7,
		"effect_description": "Target active Card gains gains No Latency",
		"image_id": 0
		},
		{
		"id": 41,
		"card_name": "Giant Rabbit Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 4,
		"value": 2,
		"effect": 8,
		"effect_description": "Remove 1 Latency to each growth on your side of the field",
		"image_id": 0
		},
		{
		"id": 42,
		"card_name": "Giant Beaver",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 6,
		"value": 2,
		"effect": 9,
		"effect_description": "Choose one tapped Growth Card and untap it",
		"image_id": 0
		},
		{
		"id": 43,
		"card_name": "Giant Wasp",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 5,
		"value": 2,
		"effect": 10,
		"effect_description": "Choose an active card and poison it (it is destroyed in 2 turns)",
		"image_id": 0
		},
		{
		"id": 44,
		"card_name": "Giant Badger",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 5,
		"value": 2,
		"effect": 11,
		"effect_description": "Restores 1 card from Extinction Deck",
		"image_id": 0
		},
		{
		"id": 45,
		"card_name": "Giant Squirrel",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 3,
		"value": 2,
		"effect": 12,
		"effect_description": "Target Growth card doubles its energy during turn",
		"image_id": 0
		},
		{
		"id": 46,
		"card_name": "Giant Poisonous Dart Frog",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 6,
		"value": 2,
		"effect": 13,
		"effect_description": "Remove target Active card from play",
		"image_id": 0
		},
		{
		"id": 47,
		"card_name": "Giant Sheep",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 6,
		"value": 2,
		"effect": 14,
		"effect_description": "Deal 1 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 48,
		"card_name": "Giant Cricket Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 7,
		"value": 2,
		"effect": 15,
		"effect_description": "Deal 2 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 49,
		"card_name": "Giant Cricket Plague",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 8,
		"value": 2,
		"effect": 16,
		"effect_description": "Deal 1 damage to all Growth Cards",
		"image_id": 0
		},
		{
		"id": 50,
		"card_name": "Giant Cat",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 4,
		"value": 2,
		"effect": 17,
		"effect_description": "Deal 2 damage to Active card",
		"image_id": 0
		},
		{
		"id": 51,
		"card_name": "Giant Jackal",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 5,
		"value": 2,
		"effect": 18,
		"effect_description": "Deal 3 damage to Active card",
		"image_id": 0
		},
		{
		"id": 52,
		"card_name": "Giant Pig",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 4,
		"value": 2,
		"effect": 19,
		"effect_description": "Destroy target Fauna and Fungi card in an active field",
		"image_id": 0
		},
		{
		"id": 53,
		"card_name": "Giant Scorpion",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 6,
		"value": 2,
		"effect": 20,
		"effect_description": "Poison touch (an active or growth card that takes damage from this card is destroyed in two turns)",
		"image_id": 0
		},
		{
		"id": 54,
		"card_name": "Giant Spider Monkey",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 6,
		"value": 2,
		"effect": 21,
		"effect_description": "Target Growth card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 55,
		"card_name": "Giant Goose",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 5,
		"value": 2,
		"effect": 22,
		"effect_description": "Target Active card must be payed or be turned if its energy cost isnt payed.",
		"image_id": 0
		},
		{
		"id": 56,
		"card_name": "Giant Mosquito Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 2,
		"value": 2,
		"effect": 23,
		"effect_description": "No Latency, this cards is destyed at the end of the turn.",
		"image_id": 0
		},
		{
		"id": 57,
		"card_name": "Giant Migrating Flock",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 5,
		"value": 2,
		"effect": 24,
		"effect_description": "Each player draws 3 growth Cards and replaces all three active growth cards",
		"image_id": 0
		},
		{
		"id": 58,
		"card_name": "Giant Cocoon",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 4,
		"value": 2,
		"effect": 25,
		"effect_description": "Each player draws 1 card from Active deck",
		"image_id": 0
		},
		{
		"id": 59,
		"card_name": "Giant Metamorphosis",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 4,
		"value": 2,
		"effect": 26,
		"effect_description": "Target player draws 2 cards from Active deck",
		"image_id": 0
		},
		{
		"id": 60,
		"card_name": "Giant Woodpecker",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 4,
		"value": 2,
		"effect": 27,
		"effect_description": "Target player draws 1 growth card",
		"image_id": 0
		},
		{
		"id": 61,
		"card_name": "Giant Swallow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 5,
		"value": 2,
		"effect": 28,
		"effect_description": "Target player draws 2 growth cards",
		"image_id": 0
		},
		{
		"id": 62,
		"card_name": "Giant Dung Beetle",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 5,
		"value": 2,
		"effect": 29,
		"effect_description": "Target Growth card gains Shield.",
		"image_id": 0
		},
		{
		"id": 63,
		"card_name": "Giant Mole",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 4,
		"value": 2,
		"effect": 30,
		"effect_description": "Target Growth Card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 64,
		"card_name": "Giant Snake Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 6,
		"value": 2,
		"effect": 31,
		"effect_description": "Target Growth card gains Shield",
		"image_id": 0
		},
		{
		"id": 65,
		"card_name": "Giant Leaf Bug",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 6,
		"value": 2,
		"effect": 32,
		"effect_description": "When this card is destroyed it becomes a Fauna and Fungos card with the effect, you can tap this card to add 2 energy to one summoning.",
		"image_id": 0
		},
		{
		"id": 66,
		"card_name": "Giant Termite",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 2,
		"type_name": "Active",
		"cost": 3,
		"value": 2,
		"effect": 33,
		"effect_description": "Deals double damage to Growth",
		"image_id": 0
		},
		{
		"id": 67,
		"card_name": "Dire Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 3,
		"value": 3,
		"effect": 1,
		"effect_description": "",
		"image_id": 0
		},
		{
		"id": 68,
		"card_name": "Dire Army Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 5,
		"value": 3,
		"effect": 2,
		"effect_description": "Trample (If this card defeats an opponent's active card, it deals the leftover robustness to the Growth card behind it)",
		"image_id": 0
		},
		{
		"id": 69,
		"card_name": "Dire Cricket",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 4,
		"value": 3,
		"effect": 3,
		"effect_description": "No Latency (This card can activate or attack on the turn it is summoned)",
		"image_id": 0
		},
		{
		"id": 70,
		"card_name": "Dire Newton",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 4,
		"value": 3,
		"effect": 4,
		"effect_description": "Shield (the first time this active card takes damage, the damage is reduced to 0, it then looses this ability)",
		"image_id": 0
		},
		{
		"id": 71,
		"card_name": "Dire Owl",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 5,
		"value": 3,
		"effect": 5,
		"effect_description": "Direct attack (this active card can attack an oponent's growth card directly)",
		"image_id": 0
		},
		{
		"id": 72,
		"card_name" : "",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 4,
		"value": 3,
		"effect": 6,
		"effect_description": "When summoned, this card increases its robustness by 3 until the start of its next turn",
		"image_id": 0
		},
		{
		"id": 73,
		"card_name": "Dire Bees",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 6,
		"value": 3,
		"effect": 7,
		"effect_description": "Target active Card gains gains No Latency",
		"image_id": 0
		},
		{
		"id": 74,
		"card_name": "Dire Rabbit Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 5,
		"value": 3,
		"effect": 8,
		"effect_description": "Remove 1 Latency to each growth on your side of the field",
		"image_id": 0
		},
		{
		"id": 75,
		"card_name": "Dire Beaver",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 7,
		"value": 3,
		"effect": 9,
		"effect_description": "Choose one tapped Growth Card and untap it",
		"image_id": 0
		},
		{
		"id": 76,
		"card_name": "Dire Wasp",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 6,
		"value": 3,
		"effect": 10,
		"effect_description": "Choose an active card and poison it (it is destroyed in 2 turns)",
		"image_id": 0
		},
		{
		"id": 77,
		"card_name": "Dire Badger",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 6,
		"value": 3,
		"effect": 11,
		"effect_description": "Restores 1 card from Extinction Deck",
		"image_id": 0
		},
		{
		"id": 78,
		"card_name": "Dire Squirrel",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 4,
		"value": 3,
		"effect": 12,
		"effect_description": "Target Growth card doubles its energy during turn",
		"image_id": 0
		},
		{
		"id": 79,
		"card_name": "Dire Poisonous Dart Frog",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 7,
		"value": 3,
		"effect": 13,
		"effect_description": "Remove target Active card from play",
		"image_id": 0
		},
		{
		"id": 80,
		"card_name": "Dire Sheep",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 7,
		"value": 3,
		"effect": 14,
		"effect_description": "Deal 1 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 81,
		"card_name": "Dire Cricket Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 8,
		"value": 3,
		"effect": 15,
		"effect_description": "Deal 2 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 82,
		"card_name": "Dire Cricket Plague",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 9,
		"value": 3,
		"effect": 16,
		"effect_description": "Deal 1 damage to all Growth Cards",
		"image_id": 0
		},
		{
		"id": 83,
		"card_name": "Dire Cat",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 5,
		"value": 3,
		"effect": 17,
		"effect_description": "Deal 2 damage to Active card",
		"image_id": 0
		},
		{
		"id": 84,
		"card_name": "Dire Jackal",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 6,
		"value": 3,
		"effect": 18,
		"effect_description": "Deal 3 damage to Active card",
		"image_id": 0
		},
		{
		"id": 85,
		"card_name": "Dire Pig",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 5,
		"value": 3,
		"effect": 19,
		"effect_description": "Destroy target Fauna and Fungi card in an active field",
		"image_id": 0
		},
		{
		"id": 86,
		"card_name": "Dire Scorpion",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 7,
		"value": 3,
		"effect": 20,
		"effect_description": "Poison touch (an active or growth card that takes damage from this card is destroyed in two turns)",
		"image_id": 0
		},
		{
		"id": 87,
		"card_name": "Dire Spider Monkey",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 7,
		"value": 3,
		"effect": 21,
		"effect_description": "Target Growth card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 88,
		"card_name": "Dire Goose",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 6,
		"value": 3,
		"effect": 22,
		"effect_description": "Target Active card must be payed or be turned if its energy cost isnt payed.",
		"image_id": 0
		},
		{
		"id": 89,
		"card_name": "Dire Mosquito Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 3,
		"value": 3,
		"effect": 23,
		"effect_description": "No Latency, this cards is destyed at the end of the turn.",
		"image_id": 0
		},
		{
		"id": 90,
		"card_name": "Dire Migrating Flock",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 6,
		"value": 3,
		"effect": 24,
		"effect_description": "Each player draws 3 growth Cards and replaces all three active growth cards",
		"image_id": 0
		},
		{
		"id": 91,
		"card_name": "Dire Cocoon",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 5,
		"value": 3,
		"effect": 25,
		"effect_description": "Each player draws 1 card from Active deck",
		"image_id": 0
		},
		{
		"id": 92,
		"card_name": "Dire Metamorphosis",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 5,
		"value": 3,
		"effect": 26,
		"effect_description": "Target player draws 2 cards from Active deck",
		"image_id": 0
		},
		{
		"id": 93,
		"card_name": "Dire Woodpecker",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 5,
		"value": 3,
		"effect": 27,
		"effect_description": "Target player draws 1 growth card",
		"image_id": 0
		},
		{
		"id": 94,
		"card_name": "Dire Swallow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 6,
		"value": 3,
		"effect": 28,
		"effect_description": "Target player draws 2 growth cards",
		"image_id": 0
		},
		{
		"id": 95,
		"card_name": "Dire Dung Beetle",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 6,
		"value": 3,
		"effect": 29,
		"effect_description": "Target Growth card gains Shield.",
		"image_id": 0
		},
		{
		"id": 96,
		"card_name": "Dire Mole",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 5,
		"value": 3,
		"effect": 30,
		"effect_description": "Target Growth Card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 97,
		"card_name": "Dire Snake Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 7,
		"value": 3,
		"effect": 31,
		"effect_description": "Target Growth card gains Shield",
		"image_id": 0
		},
		{
		"id": 98,
		"card_name": "Dire Leaf Bug",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 7,
		"value": 3,
		"effect": 32,
		"effect_description": "When this card is destroyed it becomes a Fauna and Fungos card with the effect, you can tap this card to add 2 energy to one summoning.",
		"image_id": 0
		},
		{
		"id": 99,
		"card_name": "Dire Termite",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Active",
		"cost": 4,
		"value": 3,
		"effect": 33,
		"effect_description": "Deals double damage to Growth",
		"image_id": 0
		},
		{
		"id": 100,
		"card_name": "Enchanted Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 4,
		"value": 4,
		"effect": 1,
		"effect_description": "",
		"image_id": 0
		},
		{
		"id": 101,
		"card_name": "Enchanted Army Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 2,
		"effect_description": "Trample (If this card defeats an opponent's active card, it deals the leftover robustness to the Growth card behind it)",
		"image_id": 0
		},
		{
		"id": 102,
		"card_name": "Enchanted Cricket",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 3,
		"effect_description": "No Latency (This card can activate or attack on the turn it is summoned)",
		"image_id": 0
		},
		{
		"id": 103,
		"card_name": "Enchanted Newton",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 4,
		"effect_description": "Shield (the first time this active card takes damage, the damage is reduced to 0, it then looses this ability)",
		"image_id": 0
		},
		{
		"id": 104,
		"card_name": "Enchanted Owl",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 5,
		"effect_description": "Direct attack (this active card can attack an oponent's growth card directly)",
		"image_id": 0
		},
		{
		"id": 105,
		"card_name" : "",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 6,
		"effect_description": "When summoned, this card increases its robustness by 3 until the start of its next turn",
		"image_id": 0
		},
		{
		"id": 106,
		"card_name": "Enchanted Bees",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 7,
		"value": 4,
		"effect": 7,
		"effect_description": "Target active Card gains gains No Latency",
		"image_id": 0
		},
		{
		"id": 107,
		"card_name": "Enchanted Rabbit Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 8,
		"effect_description": "Remove 1 Latency to each growth on your side of the field",
		"image_id": 0
		},
		{
		"id": 108,
		"card_name": "Enchanted Beaver",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 8,
		"value": 4,
		"effect": 9,
		"effect_description": "Choose one tapped Growth Card and untap it",
		"image_id": 0
		},
		{
		"id": 109,
		"card_name": "Enchanted Wasp",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 7,
		"value": 4,
		"effect": 10,
		"effect_description": "Choose an active card and poison it (it is destroyed in 2 turns)",
		"image_id": 0
		},
		{
		"id": 110,
		"card_name": "Enchanted Badger",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 7,
		"value": 4,
		"effect": 11,
		"effect_description": "Restores 1 card from Extinction Deck",
		"image_id": 0
		},
		{
		"id": 111,
		"card_name": "Enchanted Squirrel",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 12,
		"effect_description": "Target Growth card doubles its energy during turn",
		"image_id": 0
		},
		{
		"id": 112,
		"card_name": "Enchanted Poisonous Dart Frog",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 8,
		"value": 4,
		"effect": 13,
		"effect_description": "Remove target Active card from play",
		"image_id": 0
		},
		{
		"id": 113,
		"card_name": "Enchanted Sheep",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 8,
		"value": 4,
		"effect": 14,
		"effect_description": "Deal 1 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 114,
		"card_name": "Enchanted Cricket Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 9,
		"value": 4,
		"effect": 15,
		"effect_description": "Deal 2 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 115,
		"card_name": "Enchanted Cricket Plague",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 20,
		"value": 4,
		"effect": 16,
		"effect_description": "Deal 1 damage to all Growth Cards",
		"image_id": 0
		},
		{
		"id": 116,
		"card_name": "Enchanted Cat",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 17,
		"effect_description": "Deal 2 damage to Active card",
		"image_id": 0
		},
		{
		"id": 117,
		"card_name": "Enchanted Jackal",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 7,
		"value": 4,
		"effect": 18,
		"effect_description": "Deal 3 damage to Active card",
		"image_id": 0
		},
		{
		"id": 118,
		"card_name": "Enchanted Pig",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 19,
		"effect_description": "Destroy target Fauna and Fungi card in an active field",
		"image_id": 0
		},
		{
		"id": 119,
		"card_name": "Enchanted Scorpion",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 8,
		"value": 4,
		"effect": 20,
		"effect_description": "Poison touch (an active or growth card that takes damage from this card is destroyed in two turns)",
		"image_id": 0
		},
		{
		"id": 120,
		"card_name": "Enchanted Spider Monkey",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 8,
		"value": 4,
		"effect": 21,
		"effect_description": "Target Growth card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 121,
		"card_name": "Enchanted Goose",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 7,
		"value": 4,
		"effect": 22,
		"effect_description": "Target Active card must be payed or be turned if its energy cost isnt payed.",
		"image_id": 0
		},
		{
		"id": 122,
		"card_name": "Enchanted Mosquito Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 4,
		"value": 4,
		"effect": 23,
		"effect_description": "No Latency, this cards is destyed at the end of the turn.",
		"image_id": 0
		},
		{
		"id": 123,
		"card_name": "Enchanted Migrating Flock",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 7,
		"value": 4,
		"effect": 24,
		"effect_description": "Each player draws 3 growth Cards and replaces all three active growth cards",
		"image_id": 0
		},
		{
		"id": 124,
		"card_name": "Enchanted Cocoon",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 25,
		"effect_description": "Each player draws 1 card from Active deck",
		"image_id": 0
		},
		{
		"id": 125,
		"card_name": "Enchanted Metamorphosis",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 26,
		"effect_description": "Target player draws 2 cards from Active deck",
		"image_id": 0
		},
		{
		"id": 126,
		"card_name": "Enchanted Woodpecker",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 27,
		"effect_description": "Target player draws 1 growth card",
		"image_id": 0
		},
		{
		"id": 127,
		"card_name": "Enchanted Swallow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 7,
		"value": 4,
		"effect": 28,
		"effect_description": "Target player draws 2 growth cards",
		"image_id": 0
		},
		{
		"id": 128,
		"card_name": "Enchanted Dung Beetle",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 7,
		"value": 4,
		"effect": 29,
		"effect_description": "Target Growth card gains Shield.",
		"image_id": 0
		},
		{
		"id": 129,
		"card_name": "Enchanted Mole",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 30,
		"effect_description": "Target Growth Card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 130,
		"card_name": "Enchanted Snake Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 8,
		"value": 4,
		"effect": 31,
		"effect_description": "Target Growth card gains Shield",
		"image_id": 0
		},
		{
		"id": 131,
		"card_name": "Enchanted Leaf Bug",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 8,
		"value": 4,
		"effect": 32,
		"effect_description": "When this card is destroyed it becomes a Fauna and Fungos card with the effect, you can tap this card to add 2 energy to one summoning.",
		"image_id": 0
		},
		{
		"id": 132,
		"card_name": "Enchanted Termite",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 4,
		"type_name": "Active",
		"cost": 6,
		"value": 4,
		"effect": 33,
		"effect_description": "Deals double damage to Growth",
		"image_id": 0
		},
		{
		"id": 133,
		"card_name": "Monster Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 5,
		"value": 5,
		"effect": 1,
		"effect_description": "",
		"image_id": 0
		},
		{
		"id": 134,
		"card_name": "Monster Army Ant",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 2,
		"effect_description": "Trample (If this card defeats an opponent's active card, it deals the leftover robustness to the Growth card behind it)",
		"image_id": 0
		},
		{
		"id": 135,
		"card_name": "Monster Cricket",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 3,
		"effect_description": "No Latency (This card can activate or attack on the turn it is summoned)",
		"image_id": 0
		},
		{
		"id": 136,
		"card_name": "Monster Newton",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 4,
		"effect_description": "Shield (the first time this active card takes damage, the damage is reduced to 0, it then looses this ability)",
		"image_id": 0
		},
		{
		"id": 137,
		"card_name": "Monster Owl",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 5,
		"effect_description": "Direct attack (this active card can attack an oponent's growth card directly)",
		"image_id": 0
		},
		{
		"id": 138,
		"card_name" : "",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 6,
		"effect_description": "When summoned, this card increases its robustness by 3 until the start of its next turn",
		"image_id": 0
		},
		{
		"id": 139,
		"card_name": "Monster Bees",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 8,
		"value": 5,
		"effect": 7,
		"effect_description": "Target active Card gains gains No Latency",
		"image_id": 0
		},
		{
		"id": 140,
		"card_name": "Monster Rabbit Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 8,
		"effect_description": "Remove 1 Latency to each growth on your side of the field",
		"image_id": 0
		},
		{
		"id": 141,
		"card_name": "Monster Beaver",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 9,
		"value": 5,
		"effect": 9,
		"effect_description": "Choose one tapped Growth Card and untap it",
		"image_id": 0
		},
		{
		"id": 142,
		"card_name": "Monster Wasp",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 8,
		"value": 5,
		"effect": 10,
		"effect_description": "Choose an active card and poison it (it is destroyed in 2 turns)",
		"image_id": 0
		},
		{
		"id": 143,
		"card_name": "Monster Badger",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 8,
		"value": 5,
		"effect": 11,
		"effect_description": "Restores 1 card from Extinction Deck",
		"image_id": 0
		},
		{
		"id": 144,
		"card_name": "Monster Squirrel",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 12,
		"effect_description": "Target Growth card doubles its energy during turn",
		"image_id": 0
		},
		{
		"id": 145,
		"card_name": "Monster Poisonous Dart Frog",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 9,
		"value": 5,
		"effect": 13,
		"effect_description": "Remove target Active card from play",
		"image_id": 0
		},
		{
		"id": 146,
		"card_name": "Monster Sheep",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 9,
		"value": 5,
		"effect": 14,
		"effect_description": "Deal 1 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 147,
		"card_name": "Monster Cricket Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 20,
		"value": 5,
		"effect": 15,
		"effect_description": "Deal 2 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 148,
		"card_name": "Monster Cricket Plague",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 30,
		"value": 5,
		"effect": 16,
		"effect_description": "Deal 1 damage to all Growth Cards",
		"image_id": 0
		},
		{
		"id": 149,
		"card_name": "Monster Cat",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 17,
		"effect_description": "Deal 2 damage to Active card",
		"image_id": 0
		},
		{
		"id": 150,
		"card_name": "Monster Jackal",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 8,
		"value": 5,
		"effect": 18,
		"effect_description": "Deal 3 damage to Active card",
		"image_id": 0
		},
		{
		"id": 151,
		"card_name": "Monster Pig",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 19,
		"effect_description": "Destroy target Fauna and Fungi card in an active field",
		"image_id": 0
		},
		{
		"id": 152,
		"card_name": "Monster Scorpion",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 9,
		"value": 5,
		"effect": 20,
		"effect_description": "Poison touch (an active or growth card that takes damage from this card is destroyed in two turns)",
		"image_id": 0
		},
		{
		"id": 153,
		"card_name": "Monster Spider Monkey",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 9,
		"value": 5,
		"effect": 21,
		"effect_description": "Target Growth card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 154,
		"card_name": "Monster Goose",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 8,
		"value": 5,
		"effect": 22,
		"effect_description": "Target Active card must be payed or be turned if its energy cost isnt payed.",
		"image_id": 0
		},
		{
		"id": 155,
		"card_name": "Monster Mosquito Swarm",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 5,
		"value": 5,
		"effect": 23,
		"effect_description": "No Latency, this cards is destyed at the end of the turn.",
		"image_id": 0
		},
		{
		"id": 156,
		"card_name": "Monster Migrating Flock",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 8,
		"value": 5,
		"effect": 24,
		"effect_description": "Each player draws 3 growth Cards and replaces all three active growth cards",
		"image_id": 0
		},
		{
		"id": 157,
		"card_name": "Monster Cocoon",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 25,
		"effect_description": "Each player draws 1 card from Active deck",
		"image_id": 0
		},
		{
		"id": 158,
		"card_name": "Monster Metamorphosis",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 26,
		"effect_description": "Target player draws 2 cards from Active deck",
		"image_id": 0
		},
		{
		"id": 159,
		"card_name": "Monster Woodpecker",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 27,
		"effect_description": "Target player draws 1 growth card",
		"image_id": 0
		},
		{
		"id": 160,
		"card_name": "Monster Swallow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 8,
		"value": 5,
		"effect": 28,
		"effect_description": "Target player draws 2 growth cards",
		"image_id": 0
		},
		{
		"id": 161,
		"card_name": "Monster Dung Beetle",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 8,
		"value": 5,
		"effect": 29,
		"effect_description": "Target Growth card gains Shield.",
		"image_id": 0
		},
		{
		"id": 162,
		"card_name": "Monster Mole",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 30,
		"effect_description": "Target Growth Card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 163,
		"card_name": "Monster Snake Burrow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 9,
		"value": 5,
		"effect": 31,
		"effect_description": "Target Growth card gains Shield",
		"image_id": 0
		},
		{
		"id": 164,
		"card_name": "Monster Leaf Bug",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 9,
		"value": 5,
		"effect": 32,
		"effect_description": "When this card is destroyed it becomes a Fauna and Fungos card with the effect, you can tap this card to add 2 energy to one summoning.",
		"image_id": 0
		},
		{
		"id": 165,
		"card_name": "Monster Termite",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 5,
		"type_name": "Active",
		"cost": 7,
		"value": 5,
		"effect": 33,
		"effect_description": "Deals double damage to Growth",
		"image_id": 0
		},
	]
	var card
	for card_data in active_dict:
		_def_active_cards[card_data.id] = card_data
		_total_cards += 1


func load_default_growth_cards():
	var growth_dict = [
		{
			"id": 0,
			"card_name": "Red Maple",
			"description": "A quick growing vibrant tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "1",
			"type_name": "Growth",
			"cost": 0,
			"value": 1,
			"effect": 1,
			"effect_description": "",
			"image_id": 0
			},
			{
			"id": 2,
			"card_name": "Rooting Sappling",
			"description": "Filled with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "0",
			"type_name": "Growth",
			"cost": 1,
			"value": 1,
			"effect": 2,
			"effect_description": "Passive: The top active tree card increases its Robustness by 1",
			"image_id": 0
			},
			{
			"id": 3,
			"card_name": "Rooting Tree",
			"description": "Filling life around it with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "1",
			"type_name": "Growth",
			"cost": 2,
			"value": 1,
			"effect": 3,
			"effect_description": "Passive: The top active tree card increases its Robustness by 2",
			"image_id": 0
			},
			{
			"id": 4,
			"card_name": "Earthbinding Sappling",
			"description": "Strengthen's the soil",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "0",
			"type_name": "Growth",
			"cost": 2,
			"value": 1,
			"effect": 4,
			"effect_description": "Passive: All top active tree cards increase their Robustnes by 1",
			"image_id": 0
			},
			{
			"id": 5,
			"card_name": "Rooting Elder Tree",
			"description": "Sturdy it offers great strength to its environment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "1",
			"type_name": "Growth",
			"cost": 3,
			"value": 1,
			"effect": 5,
			"effect_description": "Passive: The top active tree card increases its Robustness by 3",
			"image_id": 0
			},
			{
			"id": 6,
			"card_name": "Cleansing Tree",
			"description": "A quick growing vibrant tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "1",
			"type_name": "Growth",
			"cost": 1,
			"value": 1,
			"effect": 6,
			"effect_description": "Reveal: Remove 1 latency from a growth card on the field",
			"image_id": 0
			},
			{
			"id": 7,
			"card_name": "Apple tree",
			"description": "Its fruits and leaves feed life around it",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "0",
			"type_name": "Growth",
			"cost": 3,
			"value": 1,
			"effect": 7,
			"effect_description": "Passive: All other growths start with 1 less latency when put in your Growth Field",
			"image_id": 0
			},
			{
			"id": 8,
			"card_name": "Polinator Flower",
			"description": "It sheds its polén to great distances",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "1",
			"type_name": "Growth",
			"cost": 1,
			"value": 1,
			"effect": 8,
			"effect_description": "Reveal: Deal 1 damage to enemy active card",
			"image_id": 0
			},
			{
			"id": 9,
			"card_name": "Cork-oak Sappling",
			"description": "Coated in protective bark",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "0",
			"type_name": "Growth",
			"cost": 2,
			"value": 1,
			"effect": 9,
			"effect_description": "Reveal: Has Shield",
			"image_id": 0
			},
			{
			"id": 10,
			"card_name": "Barrel Cactus",
			"description": "Extremely resistance to lack of nourishment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "1",
			"type_name": "Growth",
			"cost": 4,
			"value": 1,
			"effect": 10,
			"effect_description": "Passive: While this card is on the growth field, you only lose when you have 7 cards in the extinction deck",
			"image_id": 0
			},
			{
			"id": 11,
			"card_name": "Weeping Willow",
			"description": "A quick growing melancholic tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 1,
			"value": "2",
			"effect": 1,
			"effect_description": "",
			"image_id": 0
			},
			{
			"id": 12,
			"card_name": "Rooting Grass",
			"description": "Filled with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 2,
			"value": "2",
			"effect": 2,
			"effect_description": "Passive: The top active tree card increases its Robustness by 1",
			"image_id": 0
			},
			{
			"id": 13,
			"card_name": "Rooting Shrub",
			"description": "Filling life around it with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 3,
			"value": "2",
			"effect": 3,
			"effect_description": "Passive: The top active tree card increases its Robustness by 2",
			"image_id": 0
			},
			{
			"id": 14,
			"card_name": "Earthbinding Roots",
			"description": "Strengthen's the soil",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 3,
			"value": "2",
			"effect": 4,
			"effect_description": "Passive: All top active tree cards increase their Robustnes by 1",
			"image_id": 0
			},
			{
			"id": 15,
			"card_name": "Rooting Elder Shrub",
			"description": "Sturdy it offers great strength to its environment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 4,
			"value": "2",
			"effect": 5,
			"effect_description": "Passive: The top active tree card increases its Robustness by 3",
			"image_id": 0
			},
			{
			"id": 16,
			"card_name": "Cleansing River Tree",
			"description": "A quick growing vibrant tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 2,
			"value": "2",
			"effect": 6,
			"effect_description": "Reveal: Remove 1 latency from a growth card on the field",
			"image_id": 0
			},
			{
			"id": 17,
			"card_name": "Orange tree",
			"description": "Its fruits and leaves feed life around it",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 4,
			"value": "2",
			"effect": 7,
			"effect_description": "Passive: All other growths start with 1 less latency when put in your Growth Field",
			"image_id": 0
			},
			{
			"id": 18,
			"card_name": "Polinator Tree",
			"description": "It sheds its polén to great distances",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 2,
			"value": "2",
			"effect": 8,
			"effect_description": "Reveal: Deal 1 damage to enemy active card",
			"image_id": 0
			},
			{
			"id": 19,
			"card_name": "Cork-oak Shrub",
			"description": "Coated in protective bark",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 3,
			"value": "2",
			"effect": 9,
			"effect_description": "Reveal: Has Shield",
			"image_id": 0
			},
			{
			"id": 20,
			"card_name": "Barrel Cactus Bunch",
			"description": "Extremely resistance to lack of nourishment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "2",
			"type_name": "Growth",
			"cost": 5,
			"value": "2",
			"effect": 10,
			"effect_description": "Passive: While this card is on the growth field, you only lose when you have 7 cards in the extinction deck",
			"image_id": 0
			},
			{
			"id": 21,
			"card_name": "Bambu",
			"description": "A quick growing melancholic tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 2,
			"value": "3",
			"effect": 1,
			"effect_description": "",
			"image_id": 0
			},
			{
			"id": 22,
			"card_name": "Rooting Hill",
			"description": "Filled with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 3,
			"value": "3",
			"effect": 2,
			"effect_description": "Passive: The top active tree card increases its Robustness by 1",
			"image_id": 0
			},
			{
			"id": 23,
			"card_name": "Rooting Forest",
			"description": "Filling life around it with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 4,
			"value": "3",
			"effect": 3,
			"effect_description": "Passive: The top active tree card increases its Robustness by 2",
			"image_id": 0
			},
			{
			"id": 24,
			"card_name": "Earthbinding Tree",
			"description": "Strengthen's the soil",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 4,
			"value": "3",
			"effect": 4,
			"effect_description": "Passive: All top active tree cards increase their Robustnes by 1",
			"image_id": 0
			},
			{
			"id": 25,
			"card_name": "Rooting Elder Forest",
			"description": "Sturdy it offers great strength to its environment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 5,
			"value": "3",
			"effect": 5,
			"effect_description": "Passive: The top active tree card increases its Robustness by 3",
			"image_id": 0
			},
			{
			"id": 26,
			"card_name": "Cleansing Lake Tree",
			"description": "A quick growing vibrant tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 3,
			"value": "3",
			"effect": 6,
			"effect_description": "Reveal: Remove 1 latency from a growth card on the field",
			"image_id": 0
			},
			{
			"id": 27,
			"card_name": "Pear tree",
			"description": "Its fruits and leaves feed life around it",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 5,
			"value": "3",
			"effect": 7,
			"effect_description": "Passive: All other growths start with 1 less latency when put in your Growth Field",
			"image_id": 0
			},
			{
			"id": 28,
			"card_name": "Polinator Spring Tree",
			"description": "It sheds its polén to great distances",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 3,
			"value": "3",
			"effect": 8,
			"effect_description": "Reveal: Deal 1 damage to enemy active card",
			"image_id": 0
			},
			{
			"id": 29,
			"card_name": "Cork-oak Tree",
			"description": "Coated in protective bark",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 4,
			"value": "3",
			"effect": 9,
			"effect_description": "Reveal: Has Shield",
			"image_id": 0
			},
			{
			"id": 30,
			"card_name": "Golden Barrel Cactus",
			"description": "Extremely resistance to lack of nourishment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "3",
			"type_name": "Growth",
			"cost": 6,
			"value": "3",
			"effect": 10,
			"effect_description": "Passive: While this card is on the growth field, you only lose when you have 7 cards in the extinction deck",
			"image_id": 0
			},
			{
			"id": 31,
			"card_name": "Umbrella Bambu",
			"description": "A quick growing melancholic tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 3,
			"value": "4",
			"effect": 1,
			"effect_description": "",
			"image_id": 0
			},
			{
			"id": 32,
			"card_name": "Rooting Sequoia Sappling",
			"description": "Filled with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 4,
			"value": "4",
			"effect": 2,
			"effect_description": "Passive: The top active tree card increases its Robustness by 1",
			"image_id": 0
			},
			{
			"id": 33,
			"card_name": "Rooting Sequoia Tree",
			"description": "Filling life around it with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 5,
			"value": "4",
			"effect": 3,
			"effect_description": "Passive: The top active tree card increases its Robustness by 2",
			"image_id": 0
			},
			{
			"id": 34,
			"card_name": "Earthbinding Sequoia",
			"description": "Strengthen's the soil",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 5,
			"value": "4",
			"effect": 4,
			"effect_description": "Passive: All top active tree cards increase their Robustnes by 1",
			"image_id": 0
			},
			{
			"id": 35,
			"card_name": "Rooting Elder Sequoia",
			"description": "Sturdy it offers great strength to its environment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 6,
			"value": "4",
			"effect": 5,
			"effect_description": "Passive: The top active tree card increases its Robustness by 3",
			"image_id": 0
			},
			{
			"id": 36,
			"card_name": "Cleansing Cave Tree",
			"description": "A quick growing vibrant tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 4,
			"value": "4",
			"effect": 6,
			"effect_description": "Reveal: Remove 1 latency from a growth card on the field",
			"image_id": 0
			},
			{
			"id": 37,
			"card_name": "Marmelade tree",
			"description": "Its fruits and leaves feed life around it",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 6,
			"value": "4",
			"effect": 7,
			"effect_description": "Passive: All other growths start with 1 less latency when put in your Growth Field",
			"image_id": 0
			},
			{
			"id": 38,
			"card_name": "Poisonous Savana Acacias",
			"description": "It sheds its polén to great distances",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 4,
			"value": "4",
			"effect": 8,
			"effect_description": "Reveal: Deal 1 damage to enemy active card",
			"image_id": 0
			},
			{
			"id": 39,
			"card_name": "Cork-oak Elder Tree",
			"description": "Coated in protective bark",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 5,
			"value": "4",
			"effect": 9,
			"effect_description": "Reveal: Has Shield",
			"image_id": 0
			},
			{
			"id": 40,
			"card_name": "Golden Barrel Cactus Bunch",
			"description": "Extremely resistance to lack of nourishment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 7,
			"value": "4",
			"effect": 10,
			"effect_description": "Passive: While this card is on the growth field, you only lose when you have 7 cards in the extinction deck",
			"image_id": 0
			},
			{
			"id": 41,
			"card_name": "Pond cypress",
			"description": "A quick growing melancholic tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "5",
			"type_name": "Growth",
			"cost": 3,
			"value": "5",
			"effect": 1,
			"effect_description": "",
			"image_id": 0
			},
			{
			"id": 42,
			"card_name": "Rooting Patagonian Cypress",
			"description": "Filled with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 4,
			"value": "4",
			"effect": 2,
			"effect_description": "Passive: The top active tree card increases its Robustness by 1",
			"image_id": 0
			},
			{
			"id": 43,
			"card_name": "Rooting Mediterranean cypress",
			"description": "Filling life around it with opportunity",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 5,
			"value": "4",
			"effect": 3,
			"effect_description": "Passive: The top active tree card increases its Robustness by 2",
			"image_id": 0
			},
			{
			"id": 44,
			"card_name": "Earthbinding Common Yew",
			"description": "Strengthen's the soil",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 5,
			"value": "4",
			"effect": 4,
			"effect_description": "Passive: All top active tree cards increase their Robustnes by 1",
			"image_id": 0
			},
			{
			"id": 45,
			"card_name": "Rooting Great Basin bristlecone pine",
			"description": "Sturdy it offers great strength to its environment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 6,
			"value": "4",
			"effect": 5,
			"effect_description": "Passive: The top active tree card increases its Robustness by 3",
			"image_id": 0
			},
			{
			"id": 46,
			"card_name": "Great Basin bristlecone pine",
			"description": "A quick growing vibrant tree",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 4,
			"value": "4",
			"effect": 6,
			"effect_description": "Reveal: Remove 1 latency from a growth card on the field",
			"image_id": 0
			},
			{
			"id": 47,
			"card_name": "Norway Spruce",
			"description": "Its fruits and leaves feed life around it",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 6,
			"value": "4",
			"effect": 7,
			"effect_description": "Passive: All other growths start with 1 less latency when put in your Growth Field",
			"image_id": 0
			},
			{
			"id": 48,
			"card_name": "Poisonous Palmer’s Oak",
			"description": "It sheds its polén to great distances",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 4,
			"value": "4",
			"effect": 8,
			"effect_description": "Reveal: Deal 1 damage to enemy active card",
			"image_id": 0
			},
			{
			"id": 49,
			"card_name": "Cork-oak Ancient Elder Tree",
			"description": "Coated in protective bark",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 5,
			"value": "4",
			"effect": 9,
			"effect_description": "Reveal: Has Shield",
			"image_id": 0
			},
			{
			"id": 50,
			"card_name": "Pando",
			"description": "Extremely resistance to lack of nourishment",
			"rarity": "0",
			"rarity_name": "Common",
			"type": "4",
			"type_name": "Growth",
			"cost": 7,
			"value": "4",
			"effect": 10,
			"effect_description": "Passive: While this card is on the growth field, you only lose when you have 7 cards in the extinction deck",
			"image_id": 0
		}
	]
	
	var card
	for card_data in growth_dict:
		_def_growth_cards[card_data.id] = card_data
		_total_cards += 1


func load_default_fungi_cards():
	var fungi_dict = [
		{
			"id": 197,
			"card_name": "Mob Mentality",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 1,
			"value": 0,
			"effect": 2,
			"effect_description": "Target Active gains Trample, if its destroyed or removed from play, this Fungi and effect is also destroyed.",
			"image_id": 0
			},
			{
			"id": 198,
			"card_name": "Alpha",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 2,
			"value": 0,
			"effect": 3,
			"effect_description": "Target Active gains No Latency, if its destroyed or removed from play, this Fungi and effect are also destroyed.",
			"image_id": 0
			},
			{
			"id": 199,
			"card_name": "Maternal Instinct",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 2,
			"value": 0,
			"effect": 4,
			"effect_description": "Target Active gains Shield, if its destroyed or removed from play, this Fungi and effect are also destroyed.",
			"image_id": 0
			},
			{
			"id": 200,
			"card_name": "Nocturn",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 3,
			"value": 0,
			"effect": 5,
			"effect_description": "Target Active gains Direct attack, if its destroyed or removed from play, this Fungi and effect are also destroyed.",
			"image_id": 0
			},
			{
			"id": 201,
			"card_name": "Antler Season",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 2,
			"value": 0,
			"effect": 6,
			"effect_description": "Target Active gains increases its robustness by 2, if its destroyed or removed from play, this Fungi and effect are also destroyed.",
			"image_id": 0
			},
			{
			"id": 202,
			"card_name": "Second Wind",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 6,
			"value": 0,
			"effect": 7,
			"effect_description": "You can tap this Fungi card to target Tapped Active Card and Untap it",
			"image_id": 0
			},
			{
			"id": 203,
			"card_name": "Spring",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 3,
			"value": 0,
			"effect": 8,
			"effect_description": "All Growth on your side of the field have their starting Latency reduced by 1",
			"image_id": 0
			},
			{
			"id": 204,
			"card_name": "Photosynthesis",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 5,
			"value": 0,
			"effect": 9,
			"effect_description": "All Growth give one extra energy",
			"image_id": 0
			},
			{
			"id": 205,
			"card_name": "Vaccination",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 4,
			"value": 0,
			"effect": 10,
			"effect_description": "Your Active Cards become immune to Poison",
			"image_id": 0
			},
			{
			"id": 206,
			"card_name": "Amber",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 4,
			"value": 0,
			"effect": 11,
			"effect_description": "Restores 1 card from Extinction Deck",
			"image_id": 0
			},
			{
			"id": 207,
			"card_name": "Moss",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 3,
			"type_name": "Fungi",
			"cost": 2,
			"value": 0,
			"effect": 12,
			"effect_description": "You can tap this Fungi Card to add 2 energy to a summon",
			"image_id": 0
			},
			{
			"id": 208,
			"card_name": "Death Cap",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 5,
			"value": 0,
			"effect": 13,
			"effect_description": "Tap this card and destroy it to remove a damaged Active card from play",
			"image_id": 0
			},
			{
			"id": 209,
			"card_name": "Parasitic Invasion",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 5,
			"value": 0,
			"effect": 14,
			"effect_description": "Target a Growth Card and reduce its energy production by 1 (minimum of 1). When the Growth Card is removed or destroyed this card is also destroyed.",
			"image_id": 0
			},
			{
			"id": 210,
			"card_name": "Thermite Invasion",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 6,
			"value": 0,
			"effect": 15,
			"effect_description": "Target a Growth Card and reduce its energy production by 2 (minimum of 1). When the Growth Card is removed or destroyed this card is also destroyed.",
			"image_id": 0
			},
			{
			"id": 211,
			"card_name": "Fungal Invasion",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 7,
			"value": 0,
			"effect": 16,
			"effect_description": "All Enemy Growth Cards reduce their energy production by 1 (minimum of 1).",
			"image_id": 0
			},
			{
			"id": 212,
			"card_name": "Webcaps",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 3,
			"value": 0,
			"effect": 17,
			"effect_description": "Tap this Fungi card to deal 1 damage to target active card",
			"image_id": 0
			},
			{
			"id": 213,
			"card_name": "Deadly Dapperling",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 5,
			"value": 0,
			"effect": 18,
			"effect_description": "Tap this Fungi card to deal 2 damage to target active card",
			"image_id": 0
			},
			{
			"id": 214,
			"card_name": "Pig Farm",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 3,
			"value": 0,
			"effect": 19,
			"effect_description": "Destroy this card to destroy target Fungi card",
			"image_id": 0
			},
			{
			"id": 215,
			"card_name": "Disease",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 5,
			"value": 0,
			"effect": 20,
			"effect_description": "Target Active Card gains Poison touch, if its destroyed or removed from play, this Fungi and effect are also destroyed.",
			"image_id": 0
			},
			{
			"id": 216,
			"card_name": "Cut Branches",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 5,
			"value": 0,
			"effect": 21,
			"effect_description": "Tap this Fungi card to add 1 Latency from Tapped Growth card",
			"image_id": 0
			},
			{
			"id": 217,
			"card_name": "Winter",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 4,
			"value": 0,
			"effect": 22,
			"effect_description": "Target Active card must be payed at start of turn or be turned if its energy cost isnt payed, if its destroyed or removed from play, this Fungi and effect are also destroyed.",
			"image_id": 0
			},
			{
			"id": 218,
			"card_name": "Flood",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 1,
			"value": 0,
			"effect": 23,
			"effect_description": "Tap to remove all Active Cards on the field",
			"image_id": 0
			},
			{
			"id": 219,
			"card_name": "Harvest",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 4,
			"value": 0,
			"effect": 24,
			"effect_description": "Destroy this card, so each player draws 3 growth Cards and replaces all three active growth cards",
			"image_id": 0
			},
			{
			"id": 220,
			"card_name": "Bloom",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 3,
			"value": 0,
			"effect": 25,
			"effect_description": "Tap this Fungi card, each player draws 1 card from Active deck",
			"image_id": 0
			},
			{
			"id": 221,
			"card_name": "Closed Ecosystem",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 4,
			"value": 0,
			"effect": 26,
			"effect_description": "Tap this Fungi card to draw 1 card from Active deck",
			"image_id": 0
			},
			{
			"id": 222,
			"card_name": "Forgoten Seeds",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 4,
			"value": 0,
			"effect": 27,
			"effect_description": "Tap this Fungi card, target player draws 1 growth card",
			"image_id": 0
			},
			{
			"id": 223,
			"card_name": "Saved Kernels",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 6,
			"value": 0,
			"effect": 28,
			"effect_description": "Tap this Fungi card, target player draws 2 growth cards",
			"image_id": 0
			},
			{
			"id": 224,
			"card_name": "Saved into Captivity",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 6,
			"value": 0,
			"effect": 29,
			"effect_description": "Tap this Fungi card to reduce damage taken by target growth card by 2. The growth card gains 2 latency.",
			"image_id": 0
			},
			{
			"id": 225,
			"card_name": "Early Dry Season",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 5,
			"value": 0,
			"effect": 30,
			"effect_description": "Tap this Fungi card, target Growth Card gains 1 Latency",
			"image_id": 0
			},
			{
			"id": 226,
			"card_name": "Constricting Roots",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 5,
			"value": 0,
			"effect": 32,
			"effect_description": "Target Active card becomes a Fauna and Fungos card with the effect, Growth card under it has its energy prodcution reduced by 1. If its destroyed or removed from play, this Fungi and effect are also destroyed.",
			"image_id": 0
			},
			{
			"id": 227,
			"card_name": "Wood carving adaptations",
			"description": "",
			"rarity": "0",
			"rarity_name": "Common",
			"type": 7,
			"type_name": "Fungi",
			"cost": 2,
			"value": 0,
			"effect": 33,
			"effect_description": "Target Active card deals double damage to Growth. if its destroyed or removed from play, this Fungi and effect are also destroyed.",
			"image_id": 0
		}
	]
	var card
	for card_data in fungi_dict:
		_def_fungi_cards[card_data.id] = card_data
		_total_cards += 1


func load_default_weather_cards():
	var weather_dict = [
		{
		"id": 166,
		"card_name": "Rushing Gales",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 2,
		"effect_description": "Target Active gains Trample until the end of the turn",
		"image_id": 0
		},
		{
		"id": 167,
		"card_name": "First Day of Spring",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 3,
		"value": 0,
		"effect": 3,
		"effect_description": "Target Active gains No Latency until end of the turn",
		"image_id": 0
		},
		{
		"id": 168,
		"card_name": "In the Nest",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 3,
		"value": 0,
		"effect": 4,
		"effect_description": "Target Active gains Shield until end of the turn",
		"image_id": 0
		},
		{
		"id": 169,
		"card_name": "Winged",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 5,
		"effect_description": "Target Active gains Direct attack until end of the turn",
		"image_id": 0
		},
		{
		"id": 170,
		"card_name": "Shelled",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 3,
		"value": 0,
		"effect": 6,
		"effect_description": "Target Active gains increases its robustness by 3 until the end of the turn",
		"image_id": 0
		},
		{
		"id": 171,
		"card_name": "Mating Season",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 7,
		"effect_description": "Target Tapped Active Card is Untapped",
		"image_id": 0
		},
		{
		"id": 172,
		"card_name": "Rich Rain",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 8,
		"effect_description": "Remove 1 Latency to each growth on your side of the field",
		"image_id": 0
		},
		{
		"id": 173,
		"card_name": "Mating Rivalry",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 9,
		"effect_description": "Choose one untapped Growth Card and tap it",
		"image_id": 0
		},
		{
		"id": 174,
		"card_name": "Muddy Reservoire",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 5,
		"value": 0,
		"effect": 10,
		"effect_description": "Choose an active card and Poison it (it is destroyed in 2 turns)",
		"image_id": 0
		},
		{
		"id": 175,
		"card_name": "Nature Finds a Way",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 5,
		"value": 0,
		"effect": 11,
		"effect_description": "Restores 1 card from Extinction Deck",
		"image_id": 0
		},
		{
		"id": 176,
		"card_name": "Prolenged Spring",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 3,
		"type_name": "Weather",
		"cost": 7,
		"value": 0,
		"effect": 12,
		"effect_description": "All your Growth card double their energy until the end of your turn",
		"image_id": 0
		},
		{
		"id": 177,
		"card_name": "Famine",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 6,
		"value": 0,
		"effect": 13,
		"effect_description": "Remove target Active card from play",
		"image_id": 0
		},
		{
		"id": 178,
		"card_name": "drought" ,
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 6,
		"value": 0,
		"effect": 14,
		"effect_description": "Deal 1 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 179,
		"card_name": "Prolonged Drought",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 7,
		"value": 0,
		"effect": 15,
		"effect_description": "Deal 2 damage to Growth Card",
		"image_id": 0
		},
		{
		"id": 180,
		"card_name": "Desertification",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 8,
		"value": 0,
		"effect": 16,
		"effect_description": "Deal 1 damage to all Growth Cards",
		"image_id": 0
		},
		{
		"id": 181,
		"card_name": "Hail",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 17,
		"effect_description": "Deal 2 damage to Active card",
		"image_id": 0
		},
		{
		"id": 182,
		"card_name": "Lightning",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 5,
		"value": 0,
		"effect": 18,
		"effect_description": "Deal 3 damage to Active card",
		"image_id": 0
		},
		{
		"id": 183,
		"card_name": "Conflagration",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 19,
		"effect_description": "Destroy target Fauna and Fungi card in an active field",
		"image_id": 0
		},
		{
		"id": 184,
		"card_name": "Acid Rain",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 6,
		"value": 0,
		"effect": 20,
		"effect_description": "Target Active Card gains Poison touch until the end of the turn",
		"image_id": 0
		},
		{
		"id": 185,
		"card_name": "Long Winter",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 6,
		"value": 0,
		"effect": 21,
		"effect_description": "Target Growth card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 186,
		"card_name": "Hibernation",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 5,
		"value": 0,
		"effect": 22,
		"effect_description": "Target Active card must be payed or be turned if its energy cost isnt payed.",
		"image_id": 0
		},
		{
		"id": 187,
		"card_name": "Plague",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 2,
		"value": 0,
		"effect": 23,
		"effect_description": "All Active Cards on the field are removed",
		"image_id": 0
		},
		{
		"id": 188,
		"card_name": "Agriculture",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 5,
		"value": 0,
		"effect": 24,
		"effect_description": "Each player draws 3 growth Cards and replaces all three active growth cards",
		"image_id": 0
		},
		{
		"id": 189,
		"card_name": "Limited Hunting",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 3,
		"value": 0,
		"effect": 25,
		"effect_description": "Each player draws 1 card from Active deck",
		"image_id": 0
		},
		{
		"id": 190,
		"card_name": "Protected Species",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 26,
		"effect_description": "Target player draws 2 cards from Active deck",
		"image_id": 0
		},
		{
		"id": 191,
		"card_name": "Planting",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 27,
		"effect_description": "Target player draws 1 growth card",
		"image_id": 0
		},
		{
		"id": 192,
		"card_name": "Greenhouse",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 5,
		"value": 0,
		"effect": 28,
		"effect_description": "Target player draws 2 growth cards",
		"image_id": 0
		},
		{
		"id": 193,
		"card_name": "Insecticide",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 6,
		"value": 0,
		"effect": 31,
		"effect_description": "Target Growth card gains Shield.",
		"image_id": 0
		},
		{
		"id": 194,
		"card_name": "Snow",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 4,
		"value": 0,
		"effect": 30,
		"effect_description": "Target Growth Card gains 2 Latency",
		"image_id": 0
		},
		{
		"id": 195,
		"card_name": "Overgrowth",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 6,
		"value": 0,
		"effect": 32,
		"effect_description": "Target Active card becomes a Fauna and Fungos card with the effect, Growth card under it has its energy prodcution reduced by 1.",
		"image_id": 0
		},
		{
		"id": 196,
		"card_name": "Tempest",
		"description": "",
		"rarity": "0",
		"rarity_name": "Common",
		"type": 6,
		"type_name": "Weather",
		"cost": 3,
		"value": 0,
		"effect": 33,
		"effect_description": "Target Active card deals double damage to Growth until the end of the turn",
		"image_id": 0
		}
	]
	var card
	for card_data in weather_dict:
		_def_weather_cards[card_data.id] = card_data
		_total_cards += 1




#==== Instance ====#

func instance_active_card(id):
	var card = _active_card.instance()
	var data = _def_active_cards.get(id)
	card.initialize(data)
	return card


#==== Data ====#

func get_active_card_data(id):
	return _def_active_cards.get(id)


#==== Sorting ====#

func sort_cards_by_value():
	pass



#==== Utils ====#

func get_total_cards():
	return _total_cards
